apiVersion: apps/v1
kind: Deployment
metadata:
  name: react2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react2
  template:
    metadata:
      labels:
        app: react2
    spec:
      containers:
        - name: react2
          image: raul595/react:v1
          envFrom:
            - configMapRef:
                name: app-env-config
          volumeMounts:
            - name: auto-logs
              mountPath: /root/logs
      volumes:
        - name: auto-logs
          persistentVolumeClaim:
            claimName: auto-pvc
