apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeapi
  template:
    metadata:
      labels:
        app: pokeapi
    spec:
      containers:
        - name: pokeapi
          image: raul595/pokeapi:v1 
          envFrom:
            - configMapRef:
                name: app-env-config
          volumeMounts:
            - name: auto-logs
              mountPath: /root/logs
      volumes:
        - name: auto-logs
          persistentVolumeClaim:
            claimName: auto-pvc
