apiVersion: v1
kind: Service
metadata:
  name: pokeapi-s
  labels:
    app: pokeapi
spec:
  selector:
    app: pokeapi
  type: LoadBalancer
  ports:
    - name: http-port
      protocol: TCP
      port: 82
      targetPort: 3000

