apiVersion: v1
kind: Service
metadata:
  name: react2-s
  labels:
    app: react2
spec:
  selector:
    app: react2
  type: LoadBalancer
  ports:
  - name: http-port
    protocol: TCP
    port: 82  # Puerto expuesto en el servicio
    targetPort: 80  # Puerto expuesto en el contenedor
    nodePort: 30480  # Para acceder desde el exterior (en el rango 30000-32767)